apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ihgynvtqk-python 
  janus-idp.io/tekton: ihgynvtqk-python
  backstage.io/kubernetes-id: ihgynvtqk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ihgynvtqk-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml